export const roles = [
    { id: '1', title: "Backend Developer" },
    { id: '2', title: "UI Designer" },
    { id: '3', title: "Content Writer" },
    { id: '4', title: "Marketing Associate" },
    { id: '5', title: "HR Intern" },
    { id: '6', title: "Data Analyst" },
    { id: '7', title: "Frontend Developer" },
    { id: '8', title: "Graphic Designer" },
    { id: '9', title: "Sales Manager" },
    { id: '10', title: "Product Manager" },
    { id: '11', title: "Customer Support Representative" },
    { id: '12', title: "Data Scientist" },
    { id: '13', title: "Digital Marketing Specialist" },
    { id: '14', title: "Network Engineer" },
    { id: '15', title: "Financial Analyst" },
    { id: '16', title: "UX Designer" },
    { id: '17', title: "Business Development Manager" },
    { id: '18', title: "Project Manager" },
    { id: '19', title: "Legal Counsel" },
    { id: '20', title: "System Administrator" },
];
